name: Docker CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker Build and Push (Dev)
        id: docker_build_dev
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.esbuild
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/${{ github.repository_owner }}/nightscout-librelink-up:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Docker Build and Push (Tagged)
        if: startsWith(github.ref, 'refs/tags/')
        id: docker_build_tagged
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.esbuild
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/${{ github.repository_owner }}/nightscout-librelink-up:${{github.ref_name}}
            ghcr.io/${{ github.repository_owner }}/nightscout-librelink-up:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Docker Image digest
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ${{ steps.docker_build.outputs.digest }}
